version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: my-nginx-fronted
    ports:
      - "80:80"

    depends_on:
      - db

volumes:
  db_data:
    driver: local